spring:
  datasource:
    url: jdbc:h2:file:./data/newsdb
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  application:
    name: hello-NewsBot

telegram:
  bot-token: ${BOT_TOKEN}
  chat-id: ${CHAT_ID}

news:
  feeds:
    - name: "전자신문 AI"
      url: "https://rss.etnews.com/04046.xml"
    - name: "전자신문 IT"
      url: "https://rss.etnews.com/03.xml"
    - name: "AI타임스"
      url: "https://www.aitimes.com/rss/allArticle.xml"
  count-per-feed: 4

server:
  port: ${PORT:8080}